import "./globals.css";
import { Bellefair } from 'next/font/google'

import Navbar from "../components/home/Navbar";

export const metadata = {
  title: "Space Tourism",
  description: "Generated by Next.js",
};

const bellefair = Bellefair({
  weight: ["400"],
  styles: ["regular"],
  subsets: ["latin"],
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={bellefair.className}>
        <Navbar />

        {children}
      </body>
    </html>
  );
}