import { Barlow_Condensed, Barlow } from "next/font/google";

import Destination from "@/components/images/destination";
import NavbarDestination from "@/components/destination/NavDestination";

export const metadata = {
  title: "Destination",
  description: "Generated by Next.js",
};

const barlowCondensed = Barlow_Condensed({
  weight: ["100", "400"],
  styles: ["regular"],
  subsets: ["latin"],
});

export default function DestinationLayout({ children }) {
  return (
    <>
      <Destination />

      <div
        className={`${barlowCondensed.className} justify-center md:justify-start flex text-[1.6rem] md:text-[2rem] gap-[1.5rem] uppercase tracking-[2.7px] md:tracking-[3.38px] mt-[2.4rem] md:ml-[3.85rem]`}
      >
        <p className="font-bold opacity-25">01</p>
        <p>Pick your destination</p>
      </div>

        <NavbarDestination />

      {children}
    </>
  );
}
